### ISSUE TITLE
System freeze on Linux

### ISSUE THREAD

**Issue by ExtremeCoolDude** [lukasmonk/lucaschessR#26]
It was working fine and I just did git pull  and now system freezes and after unfreeze keyboard doesn't work for a while when I try to run ./LucasR.py. Terminal spits out error, I downloaded older versions, I get the same thing, not sure what happened, I haven't touched pip modules or any system/installation/updates.

```
./LucasR.py
^[./LucasR.py: line 14: syntax error near unexpected token `n_args'
./LucasR.py: line 14: `n_args = len(sys.argv)'

```
```
Version R 1.14
Traceback (most recent call last):
  File "/home/da/Downloads/lucaschessR-R1.14/bin/LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Base/Init.py", line 18, in init
    resp = Gui.run_gui(main_procesador)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/QT/Gui.py", line 33, in run_gui
    procesador.start_with_user(user)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Procesador.py", line 92, in start_with_user
    self.configuration = Configuration.Configuration(user)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Config/Configuration.py", line 290, in __init__
    self.relee_engines()
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Config/Configuration.py", line 298, in relee_engines
    self.dic_engines = OSEngines.read_engines(Code.folder_engines)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/OS/linux/OSEngines.py", line 32, in read_engines
    bmi2 = "-bmi2" if FasterCode.bmi2() else ""
AttributeError: module 'FasterCode' has no attribute 'bmi2'
Traceback (most recent call last):
  File "/home/da/Downloads/lucaschessR-R1.14/bin/LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Base/Init.py", line 18, in init
    resp = Gui.run_gui(main_procesador)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/QT/Gui.py", line 33, in run_gui
    procesador.start_with_user(user)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Procesador.py", line 92, in start_with_user
    self.configuration = Configuration.Configuration(user)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Config/Configuration.py", line 290, in __init__
    self.relee_engines()
  File "/home/da/Downloads/lucaschessR-R1.14/bin/Code/Config/Configuration.py", line 298, in relee_engines
    self.dic_engines = OSEngines.read_engines(Code.folder_engines)
  File "/home/da/Downloads/lucaschessR-R1.14/bin/OS/linux/OSEngines.py", line 32, in read_engines
    bmi2 = "-bmi2" if FasterCode.bmi2() else ""
AttributeError: module 'FasterCode' has no attribute 'bmi2'
```
```
Version R 1.16
Traceback (most recent call last):
  File "/home/da/Downloads/lucaschessR/bin/LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/da/Downloads/lucaschessR/bin/Code/Base/Init.py", line 19, in init
    resp = Gui.run_gui(main_procesador)
  File "/home/da/Downloads/lucaschessR/bin/Code/QT/Gui.py", line 33, in run_gui
    procesador.start_with_user(user)
  File "/home/da/Downloads/lucaschessR/bin/Code/Procesador.py", line 93, in start_with_user
    self.configuration = Configuration.Configuration(user)
  File "/home/da/Downloads/lucaschessR/bin/Code/Config/Configuration.py", line 288, in __init__
    self.relee_engines()
  File "/home/da/Downloads/lucaschessR/bin/Code/Config/Configuration.py", line 296, in relee_engines
    self.dic_engines = OSEngines.read_engines(Code.folder_engines)
  File "/home/da/Downloads/lucaschessR/bin/OS/linux/OSEngines.py", line 32, in read_engines
    bmi2 = "-bmi2" if FasterCode.bmi2() else ""
AttributeError: module 'FasterCode' has no attribute 'bmi2'

```

**Comment by lukasmonk** [comment]
This requires a recompilation of FasterCode.

**Comment by ExtremeCoolDude** [comment]
I forgot where I got instructions recompile faster code the first time , but I basically did `python build`  to `lucaschessR/bin/_fastercode/linux_setup.py`. Is that what you're supposed to do ? Thanks a lot.

**Comment by lukasmonk** [comment]
LucasChessR/bin/_fastercode/linux64.sh  running this script.

**Comment by ExtremeCoolDude** [comment]
I get this error : 

```
[1/1] Cythonizing FasterCode.pyx
running build_ext
building 'FasterCode' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.9 -c FasterCode.c -o build/temp.linux-x86_64-3.9/FasterCode.o
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.9/FasterCode.o -L. -L/usr/lib -lirina -o /home/da/Downloads/lucaschessR/bin/_fastercode/source/FasterCode.cpython-39-x86_64-linux-gnu.so
cp: cannot stat './FasterCode.cpython-38-x86_64-linux-gnu.so': No such file or directory

```

I copied the `FasterCode.cpython-39-x86_64-linux-gnu` file everywhere just in case its a directory problem, but the error doesn't go away.

**Comment by lukasmonk** [comment]
It depends on the python version you work with, in your case 3.9, you have to change the line with cp.
I have changed linux.sh to: cp ./FasterCode.cpython-3?-x86_64-linux-gnu.so ../../OS/linux

**Comment by ExtremeCoolDude** [comment]
Thanks a lot for your help and well as the wonderful software. Previous version had some issue with resizing window and I had to close the whole program each time while changing boards, seems to fixed on this one, also thanks for that!
