### ISSUE TITLE
Unable to run LucasChessR on Linux

### ISSUE THREAD

**Issue by michael-i-f-george** [lukasmonk/lucaschessR#27]
Hello,

I installed the following items:
```
apt-get install python3.7

apt-get install python3-pip
apt-get install python3-dev
apt-get install python3-pyqt5
apt-get install python3-pyaudio

add-apt-repository universe
apt install python3-pip

pip3 install psutil
pip3 install pygal
pip3 install chardet

pip3 install python-chess
pip3 install Pillow
pip3 install PhotoHash
pip3 install Cython
pip3 install scandir

pip3 install sortedcontainers
pip3 install pyside2
```

When I launch LucasChess.py (lucaschessR-R1.00/bin), the cursor is changed to a cross but nothing more happen.

Within the folder "/lucaschessR-R1.00/bin", I get the following error :

```
python3 LucasR.py 

Traceback (most recent call last):
  File "LucasR.py", line 18, in <module>
    import Code.Base.Init
  File "/home/michael/lucaschessR-R1.00/bin/Code/Base/Init.py", line 5, in <module>
    from Code import Procesador
  File "/home/michael/lucaschessR-R1.00/bin/Code/Procesador.py", line 8, in <module>
    from Code import Routes
  File "/home/michael/lucaschessR-R1.00/bin/Code/Routes.py", line 6, in <module>
    from Code.Base import Game
  File "/home/michael/lucaschessR-R1.00/bin/Code/Base/Game.py", line 1, in <module>
    import FasterCode
ImportError: /home/michael/lucaschessR-R1.00/bin/OS/linux/FasterCode.cpython-36m-x86_64-linux-gnu.so: undefined symbol: move_from_string
```

```
python3.7 LucasR.py 

Traceback (most recent call last):
  File "LucasR.py", line 18, in <module>
    import Code.Base.Init
  File "/home/michael/lucaschessR-R1.00/bin/Code/Base/Init.py", line 4, in <module>
    from Code import Util
  File "/home/michael/lucaschessR-R1.00/bin/Code/Util.py", line 13, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from 'psutil' (/usr/lib/python3/dist-packages/psutil/__init__.py)
```

My default version of Python 3 seems to be 3.6.9:
```
python3 -V

Python 3.6.9
```

More recent version does not work.

What am I missing?

Kind regards,
Michaël

**Comment by lukasmonk** [comment]
You need to use 1.16 version and compile FasterCode.

**Comment by michael-i-f-george** [comment]
Thanks for the good job and for answering! :-)

Launched linux64.sh:
`./linux64.sh` 

```
Compiling FasterCode.pyx because it changed.
[1/1] Cythonizing FasterCode.pyx
running build_ext
building 'FasterCode' extension
creating build
creating build/temp.linux-x86_64-3.6
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c FasterCode.c -o build/temp.linux-x86_64-3.6/FasterCode.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/FasterCode.o -L. -lirina -o /home/michael/lucaschessR-R1.16/bin/_fastercode/source/FasterCode.cpython-36m-x86_64-linux-gnu.so
cp: impossible d'évaluer './FasterCode.cpython-38-x86_64-linux-gnu.so': Aucun fichier ou dossier de ce type

```

Last line translate to `cp: unable to evaluate './FasterCode.cpython-38-x86_64-linux-gnu.so': No such file or folder`

**Comment by lukasmonk** [comment]
You must change last line of linux64.sh, ./FasterCode.cpython-38-x86_64-linux-gnu.so  is for python 3.8, then you change -38- and write -36-.

**Comment by michael-i-f-george** [comment]
Done : still get the same issue

```
Compiling FasterCode.pyx because it changed.
[1/1] Cythonizing FasterCode.pyx
running build_ext
building 'FasterCode' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c FasterCode.c -o build/temp.linux-x86_64-3.6/FasterCode.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/FasterCode.o -L. -lirina -o /home/michael/lucaschessR-R1.16/bin/_fastercode/source/FasterCode.cpython-36m-x86_64-linux-gnu.so
cp: impossible d'évaluer './FasterCode.cpython-36-x86_64-linux-gnu.so': Aucun fichier ou dossier de ce type

```

However, I found   `FasterCode.cpython-36m-x86_64-linux-gnu.so` under `/bin/_fastercode/source/`

**Comment by michael-i-f-george** [comment]
Do you want me to send you the procedure I used on Linux?

You almost have everything.

**Comment by lukasmonk** [comment]
Yes, it can be useful for more people.

**Comment by michael-i-f-george** [comment]
Here you are, just remove the ".txt" extension:

[LucasChessOnUbuntu.md.txt](https://github.com/lukasmonk/lucaschessR/files/6290688/LucasChessOnUbuntu.md.txt)

**Comment by lukasmonk** [comment]
Thank you very much.
Added in the root of the project, if you consider another place let me know, I don't know too much about GitHub.
