### ISSUE TITLE
[Question] How to setup proper config for tactics generation ?

### ISSUE THREAD

**Issue by ExtremeCoolDude** [lukasmonk/lucaschessR#29]
When I load a pgn of my previous games, then -> utilites -> analyze game -> wrong moves -> file dialog for blunder1.pgn, either I get engine not found error or get stuck on this screen : 

![image](https://user-images.githubusercontent.com/50034073/112751439-caf4e400-8fed-11eb-945a-ddaaa337ecc0.png)

Stockfish executable has u+x permissions

bug.log from stockfish folder if its' relevant : 

```
AttributeError: 'RunEngine' object has no attribute 'stdout_lock'
Traceback (most recent call last):
  File "/home/dlucaschessR/bin/LucasR.py", line 19, in <module>
    Code.Base.Init.init()
  File "/home/dlucaschessR/bin/Code/Base/Init.py", line 24, in init
    main_procesador.stop_engines()
  File "/home/dlucaschessR/bin/Code/Procesador.py", line 323, in stop_engines
    Code.list_engine_managers.close_all()
  File "/home/dlucaschessR/bin/Code/Engines/EngineManager.py", line 22, in close_all
    engine_manager.terminar()
  File "/home/dlucaschessR/bin/Code/Engines/EngineManager.py", line 249, in terminar
    self.engine.close()
  File "/home/dlucaschessR/bin/Code/Engines/EngineRun.py", line 221, in close
    if self.pid:
AttributeError: 'RunEngine' object has no attribute 'pid'

```

**Comment by lukasmonk** [comment]
I don't understand the error, maybe it doesn't have access to stockfish, but I don't know why.
For the next update, the stockfish version will be 13.
