### ISSUE TITLE
Play Like a Grandmaster Will Not Load Database

### ISSUE THREAD

**Issue by prescient** [lukasmonk/lucaschessR#51]
I have an interesting issue where when I attempt to launch play like a grandmaster the bug.log is indicating the file is not found, but i do see it in the directory.

```
Traceback (most recent call last):
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/MainWindow/WBase.py", line 273, in run_action
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Procesador.py", line 513, in run_action
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Menus/MenuTrainings.py", line 358, in lanza
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Menus/MenuTrainings.py", line 364, in menu_run
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Menus/MenuTrainings.py", line 575, in entrenaGM
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/GM/WindowGM.py", line 63, in __init__
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/GM/GM.py", line 234, in lista_gm_personal
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/LucasChessR/UserData/Personal Training/play the london.xgm'
```

```<user>@<user>-Lenovo-Yoga-C940-14IIL:/home$ cd "/home/<user>/LucasChessR/UserData/Personal Training/"
<user>@<user>-Lenovo-Yoga-C940-14IIL:~/LucasChessR/UserData/Personal Training$ ls
'Play the London.xgm'
```
I have a sneaking suspicion that it is a capitalization issue. When I create a similar training with all lowercase letters it works just fine.

**Comment by lukasmonk** [comment]
Fixed, to the next update. 
It was treated like windows where filenames are not case sensitive.
